language: java
jdk:
  - oraclejdk8
os:
  - linux
cache:
  directories:
  - "$HOME/.gradle"
before_install:
  - openssl aes-256-cbc -K $encrypted_a9176ae2c97a_key -iv $encrypted_a9176ae2c97a_iv -in secring.gpg.enc -out secring.gpg -d
  - chmod +x gradlew
script:
  - "./gradlew build uploadArchives"
